services:
  postgres:
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_USER: iaduser
      POSTGRES_PASSWORD: iadpassword
      POSTGRES_DB: iaddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: